name: Generate SBOM

on: [push]

jobs: 
  sbom:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX CLI
        run: npm install -g @cyclonedx/bom

      - name: Generate SBOM
        run: cyclonedx-bom --output-format json --output sbom.json

      - name: Verify SBOM file exists
        run: ls -l sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
