name: Generate SBOM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cyclonedx-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install project dependencies
        run: npm install

      - name: Install CycloneDX plugin
        run: npm install @cyclonedx/bom

      - name: Generate SBOM
        run: npx cyclonedx-bom -o sbom.json

      - name: Confirm file exists
        run: ls -la sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
          
